### ISSUE TITLE
The Ghost and Molly McGee is likely returning on February 12th

### ISSUE THREAD

**Issue by SkyeChen-28** [xman2156/tgamm#1]
This isn't an official source, but the cable schedule for the Disney Channel in February was leaked here: https://cabletvt.powerrangermail.net/index.php?topic=6907.0

As stated in [this post](https://www.reddit.com/r/TheOwlHouse/comments/rxwej2/season_2b_unlikely_to_return_in_february/?utm_source=share&utm_medium=web2x&context=3) on r/TheOwlHouse:

> The cable schedule is typically leaked on a cable message board once they receive it. This is NOT an official source, and they have been known to add things after the cable schedule comes out (in fact they did it for TOH Season 2A).

> But the cable forum is typically accurate until proven otherwise, so it’s UNLIKELY (but not impossible) that TOH will return in February.

Applying this to TGAMM implies that it is likely to return in February.

**Comment by xman2156** [comment]
With Dana tweeting today that the date is coming up, right after this info came out, it’s most likely not a coincidence.
